### ISSUE TITLE
Logo offer for ubuntu install

### ISSUE THREAD

**Issue by familqasimov** [frankjuniorr/ubuntu_install#1]
Hi friend. I would like to contribute by designing a logo for your project. Do you want me to design a logo for Ubuntu installation? If you want, I will write to you a new bid for the new logo.

Best regard
Famil

**Comment by frankjuniorr** [comment]
Hi friend,
Yes please, that would be great! 
whenever you want
Thank you so much.

**Comment by frankjuniorr** [comment]
Wooooooow, awesome hahaha

all logo versios are very great!

but my favorite was the number 1

thank you so much.
